import Head from "next/head";
import { getDatabase } from "../lib/notion";
import Link from "next/link";

export default function Home({ posts }) {
  console.log(posts);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto w-full sm:w-10/12 md:w-8/12 lg:w-6/12 xl:w-6/12 p-4">
          <h1 className="font-bold text-2xl">Welcome to my blog</h1>
          {posts.map((post) => {
            const date=new Date(post.created_time).toLocaleString("en-Us",{
              month: "long",
              day: "numeric",
              year: "numeric",
              })
            return (
              <div className="flex flex-col p-5 rounded-lg border-2 border-gray-200 mt-10" key={post.id}>
                <h2 className="text-xl font-bold">{post.properties.Name.title[0].plain_text}</h2>
                <span className="text-sm">{date}</span>
                <Link href="/[post]" as={`/${post.id}`}>
                  <a className="text-sm text-center w-36 py-2.5 px-5 mt-4 font-medium text-gray-50 focus:outline-none bg-gray-600 rounded-lg border border-gray-200 hover:bg-gray-100 hover:ring-gray-800 hover:ring-1 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-20">Read more</a>
                </Link>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const database = await getDatabase("f9dfc334e89e4c2289b9bc98884b5e80");

  return {
    props: {
      posts: database,
    },
    revalidate: 1,
  };
};
